server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

env:
  var:
    service-name: api-gateway
    service-password: $2a$12$hJF
    allowed_paths: '/auth-server/login||/auth-server/service||/auth-server/token/user||/auth-server/token/service||/usuarios-api/usuarios'