server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

env:
  var:
    allowed_paths: '/auth-server/login||/auth-server/token||/usuarios-api/usuarios'