services:
  mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
volumes:
  mongodb_data: